import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Providers } from "@/app/redux/providers";
import { store } from "@/app/redux/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <div className="container p-4 bg-[#f2f2f2] h-screen w-screen mx-auto">
            <Header />
            {children}
            <Footer />
          </div>
        </body>
      </html>
    </Providers>
  );
}
